name: Release GH Action

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15
      -
        name: Release
        run: |
          npm ci
          npx semantic-release